#!/usr/bin/env python3
"""
Post Top 3 Alerts from Last 5 Minutes to Reddit
"""

import asyncio
import json
import sys
from pathlib import Path
from datetime import datetime
import pytz

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

from community_bots.reddit_bot import AIONRedditBot

def format_alert_for_reddit(alert_data: dict, rank: int) -> str:
    """Format a single alert for Reddit post"""
    alert = alert_data['alert']
    symbol = alert_data['symbol']
    pattern = alert_data['pattern']
    confidence = alert_data['confidence']
    timestamp = alert_data.get('timestamp')
    
    # Format timestamp (handle both datetime objects and strings)
    if timestamp:
        if isinstance(timestamp, str):
            try:
                # Try to parse ISO format
                from datetime import datetime
                ist = pytz.timezone('Asia/Kolkata')
                dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
                if dt.tzinfo is None:
                    dt = ist.localize(dt)
                time_str = dt.strftime("%H:%M:%S IST")
            except:
                time_str = timestamp  # Use as-is if parsing fails
        else:
            time_str = timestamp.strftime("%H:%M:%S IST")
    else:
        time_str = "N/A"
    
    # Format pattern name
    pattern_display = pattern.replace('_', ' ').title()
    
    # Get alert details
    price = alert.get('last_price', 'N/A')
    expected_move = alert.get('expected_move', 'N/A')
    signal = alert.get('signal', 'N/A')
    action = alert.get('action', 'N/A')
    
    # Format post content
    content = f"""
**Rank #{rank}: {symbol} - {pattern_display}**

📊 **Details:**
- **Confidence**: {confidence:.1%}
- **Time**: {time_str}
- **Price**: ₹{price}
- **Expected Move**: {expected_move}%
- **Signal**: {signal}
- **Action**: {action}
"""
    
    # Add additional info if available
    if 'stop_loss' in alert:
        content += f"- **Stop Loss**: ₹{alert['stop_loss']}\n"
    if 'target_price' in alert:
        content += f"- **Target Price**: ₹{alert['target_price']}\n"
    if 'description' in alert:
        content += f"\n*{alert['description']}*\n"
    
    return content.strip()

async def post_top3_alerts_to_reddit():
    """Post top 3 alerts from last 5 minutes to Reddit"""
    try:
        # Load top 3 alerts
        alerts_file = Path('/tmp/top_3_alerts.json')
        if not alerts_file.exists():
            print("❌ Top 3 alerts file not found. Run the alert extraction script first.")
            return False
        
        with open(alerts_file, 'r') as f:
            top_3_alerts = json.load(f)
        
        if not top_3_alerts:
            print("⚠️  No alerts found in the file")
            return False
        
        print(f"📊 Found {len(top_3_alerts)} alerts to post")
        
        # Format Reddit post
        ist = pytz.timezone('Asia/Kolkata')
        now = datetime.now(ist)
        
        title = f"🎯 Top 3 High-Confidence Alerts - {now.strftime('%H:%M IST')}"
        
        body = f"""# 🎯 Top 3 High-Confidence Trading Alerts

*Last 5 minutes - {now.strftime('%d %b %Y, %H:%M IST')}*

---
"""
        
        # Add each alert
        for i, alert_data in enumerate(top_3_alerts[:3], 1):
            body += format_alert_for_reddit(alert_data, i)
            body += "\n\n---\n\n"
        
        # Add footer
        body += f"""
**Disclaimer**: These alerts are generated by an algorithmic trading system. Always do your own research and trade responsibly. Past performance does not guarantee future results.

---
*Generated by AION Algo Trading System*
"""
        
        print("\n📝 Reddit Post Preview:")
        print("=" * 80)
        print(f"Title: {title}")
        print(f"\nBody:\n{body[:500]}...")
        print("=" * 80)
        
        # Initialize Reddit bot
        print("\n🤖 Initializing Reddit bot...")
        reddit_bot = AIONRedditBot()
        
        if not reddit_bot.config.get('client_id'):
            print("❌ Reddit credentials not configured. Check alerts/config/reddit_config.json")
            return False
        
        # Post to Reddit
        print("📡 Posting to Reddit...")
        success = await reddit_bot.post_update(title=title, text=body, flair="Trading Alerts")
        
        if success:
            print("✅ Successfully posted top 3 alerts to Reddit!")
            return True
        else:
            print("❌ Failed to post to Reddit")
            return False
            
    except Exception as e:
        print(f"❌ Error posting to Reddit: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = asyncio.run(post_top3_alerts_to_reddit())
    sys.exit(0 if success else 1)

